In [4]:
# --- IMPORTS ---
from tensorflow.keras.models import model_from_json
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

# --- LOAD MODEL FROM JSON + WEIGHTS ---
with open("saved_models/model_architecture.json", "r") as json_file:
    model_json = json_file.read()

model = model_from_json(model_json)
model.load_weights("saved_models/model_weights.weights.h5")

print(" Model loaded successfully for prediction.")

# --- PREPARE TEST DATA ---
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    "dataset/test",
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

# --- PREDICTION ---
predictions = model.predict(test_generator)
predicted_classes = np.argmax(predictions, axis=1)
true_labels = test_generator.classes

# --- ACCURACY & CONFUSION MATRIX ---
accuracy = accuracy_score(true_labels, predicted_classes)
cm = confusion_matrix(true_labels, predicted_classes)

print(f"\n Test Accuracy: {accuracy * 100:.2f}%")
print("\n Confusion Matrix:")
print(cm)


 Model loaded successfully for prediction.
Found 180 images belonging to 12 classes.
6/6 ━━━━━━━━━━━━━━━━━━━━ 13s 2s/step

 Test Accuracy: 15.56%

 Confusion Matrix:
[[ 0  1  2  1  0  0  0  0  0  1  0 10]
 [ 1  0  5  2  0  2  0  0  0  0  0  5]
 [ 1  0 10  0  0  0  0  0  0  0  0  4]
 [ 1  0  2  5  0  0  0  0  0  1  1  5]
 [ 0  0  9  4  0  0  0  0  0  0  0  2]
 [ 2  0  2  2  0  2  0  0  0  1  0  6]
 [ 1  1  0  0  0  2  4  0  0  6  0  1]
 [ 1  1  0  0  0  2  0  0  0  6  2  3]
 [ 1  0  0  1  0  3  0  0  0  0  0 10]
 [ 0  2  1  2  0  0  1  0  0  3  0  6]
 [ 2  1  0  0  0  2  2  0  0  3  0  5]
 [ 2  0  4  0  0  0  2  0  0  3  0  4]]
